export const COMMUNES_76 = new Set([
  "allouville-bellefosse", "alvimare", "ambrumesnil", "amfreville-la-mi-voie", "amfreville-les-champs",
  "anceaumeville", "ancourt", "ancourteville-sur-hericourt", "ancretieville-saint-victor", "ancretteville-sur-mer",
  "angerville-bailleul", "angerville-l'orcher", "angerville-la-martel", "angiens", "anglesqueville-l'esneval",
  "anglesqueville-la-bras-long", "anneville-ambourville", "anneville-sur-scie", "annouville-vilmesnil",
  "anquetierville", "anveville", "ardouval", "arelaune-en-seine", "argueil", "arques-la-bataille", "assigny",
  "aubeguimont", "aubermesnil-aux-erables", "aubermesnil-beaumais", "auberville-la-manuel", "auberville-la-renault",
  "aumale", "auppegard", "auquemesnil", "authieux-ratieville", "les authieux-sur-le-port-saint-ouen", "autigny",
  "auvilliers", "auzebosc", "auzouville-l'esneval", "auzouville-sur-ry", "auzouville-sur-saane", "avesnes-en-bray",
  "avesnes-en-val", "avremesnil", "bacqueville-en-caux", "bailleul-neuville", "baillolet", "bailly-en-riviere",
  "baons-le-comte", "bardouville", "barentin", "baromesnil", "bazinval", "beaubec-la-rosiere", "beaumont-le-hareng",
  "beaurepaire", "beaussault", "beautot", "beauval-en-caux", "beauvoir-en-lyons", "bec-de-mortagne", "belbeuf",
  "bellencombre", "bellengreville", "belleville-en-caux", "belmesnil", "benarville", "benesville", "bennetot",
  "benouville", "bermonville", "berneval-le-grand", "bernieres", "bertheauville", "bertreville", "bertreville-saint-ouen",
  "bertrimont", "berville-sur-seine", "betteville", "beuzeville-la-grenier", "beuzeville-la-guerard", "beuzevillette",
  "bezancourt", "bierville", "bihorel", "biville-la-baignarde", "biville-la-riviere", "biville-sur-mer", "blacqueville",
  "blainville-crevon", "blangy-sur-bresle", "blosseville", "le bocasse", "bois-d'ennebourg", "bois-guilbert",
  "bois-guillaume", "bois-heroult", "bois-himont", "bois-l'eveque", "boissay", "bolbec", "bolleville", "bonsecours",
  "boos", "bordeaux-saint-clair", "bornambusc", "bosc-berenger", "bosc-bordel", "bosc-edeline", "bosc-guerard-saint-adrien",
  "bosc-hyons", "bosc-le-hard", "bosc-mesnil", "bosville", "boudeville", "bouelles", "la bouille", "bourdainville",
  "le bourg-dun", "bourville", "bouville", "brachy", "bracquetuit", "bradiancourt", "brametot", "breaute",
  "bremontier-merval", "bretteville-du-grand-caux", "bretteville-saint-laurent", "buchy", "bully", "bures-en-bray",
  "butot", "butot-venesville", "cailleville", "cailly", "callengeville", "calleville-les-deux-eglises", "campneuseville",
  "canehan", "canouville", "canteleu", "canville-les-deux-eglises", "cany-barville", "carville-la-folletiere",
  "carville-pot-de-fer", "catenay", "caudebec-les-elbeuf", "le caule-sainte-beuve", "cauville-sur-mer", "les cent-acres",
  "la cerlangue", "la chapelle-du-bourgay", "la chapelle-saint-ouen", "la chapelle-sur-dun", "la chaussee", "cideville",
  "clais", "clasville", "claville-motteville", "cleon", "cleres", "cleuville", "cliponville", "colleville",
  "colmesnil-manneville", "compainville", "conteville", "contremoulins", "cottevrard", "crasville-la-mallet",
  "crasville-la-rocquefort", "criel-sur-mer", "la crique", "criquebeuf-en-caux", "criquetot-l'esneval",
  "criquetot-le-mauconduit", "criquetot-sur-longueville", "criquetot-sur-ouville", "criquiers", "croisy-sur-andelle",
  "croixdalle", "croix-mare", "cropus", "crosville-sur-scie", "cuverville", "cuverville-sur-yeres", "cuy-saint-fiacre",
  "dampierre-en-bray", "dampierre-saint-nicolas", "dancourt", "darnetal", "daubeuf-serville", "denestanville",
  "derchigny", "deville-les-rouen", "dieppe", "doudeauville", "doudeville", "douvrend", "drosay", "duclair",
  "ecalles-alix", "ecrainville", "ecretteville-les-baons", "ecretteville-sur-mer", "ectot-l'auber", "ectot-les-baons",
  "elbeuf", "elbeuf-en-bray", "elbeuf-sur-andelle", "eletot", "ellecourt", "envermeu", "envronville",
  "epinay-sur-duclair", "epouville", "epretot", "epreville", "ermenouville", "ernemont-la-villette",
  "ernemont-sur-buchy", "esclavelles", "eslettes", "esteville", "etaimpuis", "etalleville", "etainhus",
  "etoutteville", "etretat", "eu", "fallencourt", "fecamp", "ferrieres-en-bray", "la ferte-saint-samson",
  "fesques", "la feuillie", "flamanville", "flamets-fretils", "flocques", "fongueusemare", "fontaine-en-bray",
  "fontaine-la-mallet", "fontaine-le-bourg", "fontaine-le-dun", "fontaine-sous-preaux", "fontenay",
  "forges-les-eaux", "foucarmont", "foucart", "franqueville-saint-pierre", "freauville", "la frenaye",
  "fresles", "fresnay-le-long", "fresne-le-plan", "fresnoy-folny", "freulleville", "frichemesnil",
  "froberville", "fry", "fultot", "gaillefontaine", "gainneville", "gancourt-saint-etienne", "gerponville",
  "gerville", "goderville", "gommerville", "gonfreville-caillot", "gonfreville-l'orcher", "gonnetot",
  "gonneville-la-mallet", "gonneville-sur-scie", "gonzeville", "gournay-en-bray", "gouy", "grainville-la-teinturiere",
  "grainville-sur-ry", "grand-camp", "grand-couronne", "le grand-quevilly", "grandcourt", "graval", "greges",
  "gremontville", "grigneuseville", "gruchet-le-valasse", "gruchet-saint-simeon", "grugny", "grumesnil",
  "guerville", "gueures", "gueutteville", "gueutteville-les-gres", "le hanouard", "harfleur", "hattenville",
  "haucourt", "haudricourt", "haussez", "les hauts-de-caux", "hautot-l'auvray", "hautot-le-vatois",
  "hautot-saint-sulpice", "hautot-sur-fecamp", "hautot-sur-mer", "hautot-sur-seine", "le havre", "la haye",
  "henouville", "hericourt-en-caux", "hermanville", "heronchelles", "heugleville-sur-scie", "heuqueville",
  "heurteauville", "hodeng-au-bosc", "hodeng-hodenger", "le houlme", "houppeville", "houquetot",
  "hugleville-en-caux", "les ifs", "illois", "imbleville", "incheville", "ingouville", "isneauville",
  "jumieges", "lamberville", "lammerville", "landes-vieilles-et-neuves", "lanquetot", "lestanville",
  "lillebonne", "limesy", "limpiville", "lindebeuf", "lintot", "lintot-les-bois", "les loges", "la londe",
  "londinieres", "longmesnil", "longroy", "longueil", "longuerue", "longueville-sur-scie", "louvetot",
  "lucy", "luneray", "malaunay", "malleville-les-gres", "maneglise", "manehouville", "maniquerville",
  "manneville-es-plains", "manneville-la-goupil", "mannevillette", "maromme", "marques", "martainville-epreville",
  "martigny", "martin-eglise", "massy", "mathonville", "maucomble", "maulevrier-sainte-gertrude", "mauny",
  "mauquenchy", "melamare", "menerval", "menonval", "mentheville", "mesangueville", "mesnieres-en-bray",
  "le mesnil-durdent", "le mesnil-esnard", "mesnil-follemprise", "mesnil-mauger", "mesnil-panneville",
  "mesnil-raoul", "le mesnil-reaume", "le mesnil-sous-jumieges", "meulers", "millebosc", "mirville",
  "molagnies", "monchaux-soreng", "monchy-sur-eu", "mont-cauvaire", "monterolier", "montivilliers",
  "montmain", "montreuil-en-caux", "montroty", "mont-saint-aignan", "montville", "morgny-la-pommeraye",
  "mortemer", "morville-sur-andelle", "motteville", "moulineaux", "muchedent", "nesle-hodeng",
  "nesle-normandeuse", "neuf-marche", "neufbosc", "neufchatel-en-bray", "la neuville-chant-d'oisel",
  "neuville-ferrieres", "nointot", "nollevval", "normanville", "norville", "notre-dame-d'aliermont",
  "notre-dame-de-bliquetuit", "notre-dame-de-bondeville", "notre-dame-du-bec", "notre-dame-du-parc",
  "nullemont", "ocqueville", "octeville-sur-mer", "offranville", "oherville", "oissel", "omonville",
  "orival", "osmoy-saint-valery", "ouainville", "oudalle", "ourville-en-caux", "ouville-l'abbaye",
  "ouville-la-riviere", "paluel", "parc-d'anxtot", "pavilly", "petit-caux", "petit-couronne",
  "le petit-quevilly", "petiville", "pierrecourt", "pierrefiques", "pissy-poville", "pleine-seve",
  "pommereux", "pommereval", "ponts-et-marais", "port-jerome-sur-seine", "preaux", "pretot-vicquemare",
  "preuseville", "puisenval", "quevillon", "quevreville-la-poterie", "quiberville", "quievrecourt",
  "quincampoix", "raffetot", "realcamp", "regneville", "la remuee", "retonval", "reuville", "ricarville",
  "richemont", "rieux", "rives-en-seine", "riville", "robertot", "rocquefort", "rocquemont", "rogerville",
  "rolleville", "roncherolles-en-bray", "roncherolles-sur-le-vivier", "ronchois", "rosay", "rouen",
  "roumare", "routes", "rouville", "rouvray-catillon", "rouxmesnil-bouteilles", "royville", "la rue-saint-pierre",
  "ry", "saane-saint-just", "sainneville", "saint-aignan-sur-ry", "saint-andre-sur-cailly", "saint-antoine-la-foret",
  "saint-arnoult", "saint-aubin-celloville", "saint-aubin-de-cretot", "saint-aubin-epinay", "saint-aubin-les-elbeuf",
  "saint-aubin-routot", "saint-aubin-sur-mer", "saint-aubin-sur-scie", "saint-clair-sur-les-monts", "saint-crespin",
  "saint-denis-d'aclon", "saint-denis-le-thiboult", "saint-denis-sur-scie", "sainte-adresse", "sainte-agathe-d'aliermont",
  "sainte-austreberthe", "sainte-beuve-en-riviere", "sainte-colombe", "sainte-croix-sur-buchy", "sainte-foy",
  "sainte-genevieve", "sainte-helene-bondeville", "sainte-marguerite-sur-duclair", "sainte-marguerite-sur-mer",
  "sainte-marie-au-bosc", "sainte-marie-des-champs", "saint-etienne-du-rouvray", "saint-eustache-la-foret",
  "saint-georges-sur-fontaine", "saint-germain-d'etables", "saint-germain-des-essourts", "saint-germain-sous-cailly",
  "saint-germain-sur-eaulne", "saint-gilles-de-cretot", "saint-gilles-de-la-neuville", "saint-hellier",
  "saint-honore", "saint-jacques-d'aliermont", "saint-jacques-sur-darnetal", "saint-jean-de-folleville",
  "saint-jean-de-la-neuville", "saint-jean-du-cardonnay", "saint-jouin-bruneval", "saint-laurent-de-brevedent",
  "saint-laurent-en-caux", "saint-leger-aux-bois", "saint-leger-du-bourg-denis", "saint-leonard",
  "saint-maclou-de-folleville", "saint-maclou-la-briere", "saint-mards", "saint-martin-au-bosc",
  "saint-martin-aux-arbres", "saint-martin-aux-buneaux", "saint-martin-de-boscherville", "saint-martin-de-l'if",
  "saint-martin-du-bec", "saint-martin-du-manoir", "saint-martin-du-vivier", "saint-martin-l'hortier",
  "saint-martin-le-gaillard", "saint-martin-osmonville", "saint-maurice-d'etelan", "saint-michel-d'halescourt",
  "saint-nicolas-d'aliermont", "saint-nicolas-de-la-haie", "saint-nicolas-de-la-taille", "saint-ouen-du-breuil",
  "saint-ouen-le-mauger", "saint-ouen-sous-bailly", "saint-paer", "saint-pierre-de-manneville",
  "saint-pierre-de-varengeville", "saint-pierre-des-jonquieres", "saint-pierre-en-port", "saint-pierre-en-val",
  "saint-pierre-le-vieux", "saint-pierre-le-viger", "saint-remy-boscrocourt", "saint-riquier-en-riviere",
  "saint-riquier-es-plains", "saint-romain-de-colbosc", "saint-saens", "saint-saire", "saint-sauveur-d'emalleville",
  "saint-sylvain", "saint-vaast-d'equiqueville", "saint-vaast-du-val", "saint-valery-en-caux", "saint-victor-l'abbaye",
  "saint-vigor-d'ymonville", "sandouville", "sasseville", "sassetot-le-malgarde", "sassetot-le-mauconduit",
  "sauchay", "saumont-la-poterie", "sauqueville", "saussay", "sausseuzemare-en-caux", "serqueux", "sierville",
  "sigy-en-bray", "smermesnil", "sommesnil", "sommery", "sorquainville", "sotteville-les-rouen",
  "sotteville-sur-mer", "terres-de-caux", "therouldeville", "theuville-aux-maillots", "thiergeville",
  "thietreville", "le thil-riberpre", "thil-manneville", "thiouville", "tocqueville-en-caux",
  "tocqueville-les-murs", "torcy-le-grand", "torcy-le-petit", "totes", "touffreville-la-corbeline",
  "tourville-la-riviere", "tourville-les-ifs", "tourville-sur-arques", "toussaint", "le trait", "tremauville",
  "le treport", "la trinite-du-mont", "les trois-pierres", "trouville", "turretot", "val-de-la-haye",
  "val-de-saane", "val-de-scie", "valmont", "varengeville-sur-mer", "varneville-bretteville", "vassonville",
  "vatierville", "vattetot-sous-beaumont", "vattetot-sur-mer", "vatteville-la-rue", "la vaupaliere",
  "veauville-les-quelles", "venestanville", "ventes-saint-remy", "vergetot", "veules-les-roses",
  "veulettes-sur-mer", "vibeuf", "le vieux-manoir", "vieux-rouen-sur-bresle", "villainville", "villers-ecalles",
  "villers-sous-foucarmont", "villy-sur-yeres", "vinemerville", "virville", "vittefleur", "wanchy-capval",
  "yainville", "yebleron", "yerville", "ymare", "yport", "ypreville-biville", "yquebeuf", "yvecrique",
  "yvetot", "yville-sur-seine",
]);
